#! /bin/sh
#######################################################################################################
#                                                                                                     #
# read the variables for the device password from the 'urlader environment' and compute the device    #
# cipher key from them                                                                                #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# Copyright (C) 2014-2017 P.Hämmerlein (peterpawn@yourfritz.de)                                       #
#                                                                                                     #
# This program is free software; you can redistribute it and/or modify it under the terms of the GNU  #
# General Public License as published by the Free Software Foundation; either version 2 of the        #
# License, or (at your option) any later version.                                                     #
#                                                                                                     #
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   #
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      #
# General Public License under http://www.gnu.org/licenses/gpl-2.0.html for more details.             #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# The script has to be called from a FRITZ!OS environment (or at least the file for the 'urlader      #
# environment' must be present) and it reads the variable components for the device cipher key from   #
# the 'urlader environment' file on procfs.                                                           #
# If the option '-e' (or '--export') is specified, a hash value to be used as export password is      #
# computed (it contains less device specific values).                                                 #
#                                                                                                     #
# This script needs an OpenSSL binary with the 'dgst' function and MD5 support for it and another     #
# script (device_password) to compute the hash (the OpenSSL binary will be called from there).        #
# The computed hash value is written to STDOUT (in binary format), the caller is responsible for the  #
# proper redirection.                                                                                 #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# constants                                                                                           #
#                                                                                                     #
#######################################################################################################
urlader_environment="/proc/sys/urlader/environment"
serial_name="SerialNumber"
maca_name="maca"
wlan_key_name="wlan_key"
tr069_pw_name="tr069_passphrase"
needed_scripts="device_password"
#######################################################################################################
#                                                                                                     #
# check debug option                                                                                  #
#                                                                                                     #
#######################################################################################################
if [ "$1" = "-d" -o "$1" = "--debug" ]; then
	debug=1
	shift
else
	debug=0
fi
#######################################################################################################
#                                                                                                     #
# check environment                                                                                   #
#                                                                                                     #
#######################################################################################################
if [ -t 1 ]; then
	printf "Please redirect STDOUT of this script, the computed key will be written in binary to this handle.\n" 1>&2
	exit 1
fi
if ! [ -f "$urlader_environment" ]; then
	printf "File '%s' does not exist.\n" "$urlader_environment" 1>&2
	exit 1
fi
[ "$(expr "$0" : ".*\(/\).*")" = "/" ] && d="${0%/*}" || d="."
for n in $needed_scripts; do
	eval $n="$d/$n"
	eval f="\$$n"
	if ! [ -x "$f" ]; then
		printf "Missing another needed executable (%s).\n" "$n" 1>&2
		exit 1
	fi
done
#######################################################################################################
#                                                                                                     #
# check export option                                                                                 #
#                                                                                                     #
#######################################################################################################
if [ "$1" = "-e" -o "$1" = "--export" ]; then
	export=1
	shift
else
	export=0
fi
#######################################################################################################
#                                                                                                     #
# read data from environment                                                                          #
#                                                                                                     #
#######################################################################################################
serial="$(sed -n -e "s|^$serial_name[ \t]*\(.*\)\$|\1|p" "$urlader_environment")"
maca="$(sed -n -e "s|^$maca_name[ \t]*\(.*\)\$|\1|p" "$urlader_environment")"
if [ $export -eq 0 ]; then
	wlan_key="$(sed -n -e "s|^$wlan_key_name[ \t]*\(.*\)\$|\1|p" "$urlader_environment")"
	tr069_passphrase="$(sed -n -e "s|^$tr069_pw_name[ \t]*\(.*\)\$|\1|p" "$urlader_environment")"
fi
#######################################################################################################
#                                                                                                     #
# compute the hash now                                                                                #
#                                                                                                     #
#######################################################################################################
$device_password $serial $maca $wlan_key $tr069_passphrase
exit $?
#######################################################################################################
#                                                                                                     #
# end of script                                                                                       #
#                                                                                                     #
#######################################################################################################
