#! /bin/sh
#######################################################################################################
#                                                                                                     #
# compute the cipher key for AVM's implementation from a specified password                           #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# Copyright (C) 2014-2017 P.Hämmerlein (peterpawn@yourfritz.de)                                       #
#                                                                                                     #
# This program is free software; you can redistribute it and/or modify it under the terms of the GNU  #
# General Public License as published by the Free Software Foundation; either version 2 of the        #
# License, or (at your option) any later version.                                                     #
#                                                                                                     #
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   #
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      #
# General Public License under http://www.gnu.org/licenses/gpl-2.0.html for more details.             #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# The script simply computes a MD5 hash of the specified password. This hash (padded to 32 bytes) is  #
# used by AVM's implementation instead of the hash computed from the 'device identity' to encode or   #
# decode an export file.                                                                              #
#                                                                                                     #
# This script needs an OpenSSL binary with the 'dgst' function and MD5 support for it. The computed   #
# hash value is written to STDOUT, the caller is responsible for the proper redirection.              #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# check debug option                                                                                  #
#                                                                                                     #
#######################################################################################################
if [ "$1" = "-d" -o "$1" = "--debug" ]; then
	debug=1
	shift
else
	debug=0
fi
#######################################################################################################
#                                                                                                     #
# check parameters                                                                                    #
#                                                                                                     #
#######################################################################################################
if [ -t 1 ]; then
	printf "Please redirect STDOUT of this script, the computed key will be written in binary to this handle.\n" 1>&2
	exit 1
fi
if [ $# -lt 2 ]; then
	printf "Missing the password to use, please read the description from the comment block at the beginning of this script file.\n" 1>&2
	exit 1
fi
if ! openssl dgst -md5 -binary </dev/null 2>/dev/null 1>&2; then
	printf "Error calling OpenSSL to create a MD5 hash. Please check, if 'openssl' is present and supports the needed function.\n" 1>&2
	exit 1
fi
password="$1"
#######################################################################################################
#                                                                                                     #
# compute the hash now                                                                                #
#                                                                                                     #
#######################################################################################################
printf "%s" "$password" | openssl dgst -md5 -binary 2>/dev/null
exit $?
#######################################################################################################
#                                                                                                     #
# end of script                                                                                       #
#                                                                                                     #
#######################################################################################################
